### ISSUE TITLE
Options make no effect

### ISSUE THREAD

**Issue by eduarddotgg** [andyjansson/postcss-grid#1]
Hello! I'm trying to use postcss-grid with webpack. The problem is that options (margin, max-width etc) specified in var make no effect. here is example of my code. 

```
var grid = require('postcss-grid');
postcss: function () {
    return [
        grid({
            columns: 12, 
            maxWidth: 1320, 
            gutter: 0
        }),
    ];
}
```

i also tried to put options in var, it didn't work too.

**Comment by andyjansson** [comment]
Unfortunately, I have no experience with webpack. Is the plugin otherwise working, i.e. are you able to create columns and the like? Are you using [postcss-loader](https://github.com/postcss/postcss-loader)? Also, do you have a snippet to demonstrate the issue you are having?

**Comment by andyjansson** [comment]
Looks like options with `0` isn't being respected. I've committed a fix to the repository. Could you try it out and verify that it works before I publish it to npm?

**Comment by andyjansson** [comment]
Resolved.
