### ISSUE TITLE
Unnecessary display: inline

### ISSUE THREAD

**Issue by hudochenkov** [andyjansson/postcss-grid#2]
What is the point of having `display: inline` within `float`? When `float` is applied to the element, element's `display` automatically sets to `block`, so `display: inline` do nothing.

**Comment by andyjansson** [comment]
`display: inline` is there to prevent the double margin bug in older versions of Internet Explorer.

**Comment by hudochenkov** [comment]
This is only for IE6/IE7. Very few developers needed to support this browsers. Maybe by default plugin should not add this line? Option for legacy browsers should be better, in my opinion.

**Comment by andyjansson** [comment]
I'll consider moving it to an option. Any preferences?

**Comment by hudochenkov** [comment]
`legacy: true`

**Comment by andyjansson** [comment]
Fixed in v2.

**Comment by hudochenkov** [comment]
Thank you!
