### ISSUE TITLE
Last helper

### ISSUE THREAD

**Issue by vectorsize** [andyjansson/postcss-grid#4]
it would be nice to have a `last` kind of helper when using the `grid-width(...)` and `grid-gutter(...)` functions.

**Comment by andyjansson** [comment]
What would that do, exactly?

**Comment by vectorsize** [comment]
that's a good point... sorry didn't think properly before posting :) , was trying to abstract away the margin handling so one wouldn't have to do `margin-right: 0` when using the functions, but I realize it doesn't work like that since we are already working on the value level in this case.
